# NatLink macro definitions for NaturallySpeaking
# coding: latin-1
# Generated by vcl2py 2.8, Wed Dec 04 13:48:49 2013

import natlink
from natlinkutils import *
from VocolaUtils import *


class ThisGrammar(GrammarBase):

    gramSpec = """
        <1> = 'Switch Window' ;
        <2> = 'Copy and Switch' ;
        <3> = 'Copy to' ('NatSpeak' | 'Emacs' | 'Composition' ) ;
        <4> = 'Close Here' ;
        <5> = 'Close Prompt' ;
        <6> = ('Switch' | 'Next' ) 'View' ;
        <7> = ('Switch' | 'Next' ) 'View' <n> ;
        <8> = 'Previous View' ;
        <9> = 'Previous View' <n> ;
        <10> = 'Tab Back' ;
        <11> = 'Tab Back' <n> ;
        <12> = ('Expand' | 'Collapse' ) 'That' ;
        <13> = 'Dragon Menu' ;
        <14> = ('Edit' | 'Train' ) 'Words' ;
        <15> = 'Save Speech Files' ;
        <16> = 'Exit NatSpeak' ;
        <17> = 'Die Die' ;
        <18> = 'Hit Down' ;
        <19> = 'Hit Double' ;
        <20> = ('Shift' | 'Control' | 'Alt' ) 'Click' ;
        <21> = 'Hit Start' [ 'Menu' ] ;
        <n> = ('zero' | 'one' | 'two' | 'three' | 'four' | 'five' | 'six' | 'seven' | 'eight' | 'nine' | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30) ;
        <upDown> = ('Up' | 'Down' ) ;
        <leftRight> = ('Left' | 'Right' ) ;
        <22> = 'Drag' <n> <upDown> ;
        <23> = 'Drag' <n> <leftRight> ;
        <24> = 'Window' <direction> ;
        <direction> = 'Left' | 'Right' | 'Up' | 'Down' ;
        <left_right> = 'Left' | 'Right' ;
        <start_end> = ('Start' | 'End' ) ;
        <compass> = ('North' | 'South' | 'East' | 'West' ) ;
        <25> = 'Kill' ('Char' | '1' | 'One' ) ;
        <26> = 'Kill Back' [ '1' ] ;
        <27> = 'Kill' <n> ;
        <28> = [ 'Kill' ] 'Back' <n> ;
        <29> = [ 'One' ] 'Word' <left_right> ;
        <30> = <n> 'Words' <left_right> ;
        <31> = 'Kill Word' ;
        <32> = 'Kill' <32b> ;
        <32b> = <n> 'Words' ;
        <33> = 'Kill Back Word' ;
        <34> = 'Kill Back' <34b> ;
        <34b> = <n> 'Words' ;
        <35> = 'Line' <start_end> ;
        <36> = 'Line Here' ;
        <37> = 'Copy Line' ;
        <38> = 'Kill Line' ;
        <39> = 'Kill Back Line' ;
        <40> = 'Kill' <40b> ;
        <40b> = <n> 'Lines' ;
        <41> = 'Kill Back' <41b> ;
        <41b> = <n> 'Lines' ;
        <42> = 'Kill Here' ;
        <43> = 'Kill Back Here' ;
        <44> = 'Duplicate Line' ;
        <45> = 'Graph Start' ;
        <46> = 'Graph End' ;
        <47> = ('Paragraph' | 'Graph' ) 'Here' ;
        <48> = 'Open' ('Graph' | 'Line' ) ;
        <49> = 'Copy Graph' ;
        <50> = 'Kill Graph' ;
        <51> = 'Duplicate Graph' ;
        <52> = 'Flow Start' ;
        <53> = 'Flow End' ;
        <54> = 'Select All' ;
        <55> = 'Copy All' ;
        <56> = ('Cut' | 'Kill' ) 'All' ;
        <57> = 'Kill Flow Here' ;
        <58> = 'Kill Back Flow Here' ;
        <59> = 'Replace All' ;
        <60> = 'Kill That' ;
        <61> = 'Yank That' ;
        <62> = 'Paste Here' ;
        <63> = 'Duplicate That' ;
        <64> = 'Keep That' ;
        <65> = 'Select' <compass> ;
        <66> = 'undo that' <n> ;
        <67> = 'Camel' [ 'Case' ] 'That' ;
        <68> = ('Cap' | 'Up Case' ) <n> ;
        <key> = ('alpha' | 'bravo' | 'charlie' | 'delta' | 'echo' | 'foxtrot' | 'golf' | 'hotel' | 'india' | 'juliett' | 'kilo' | 'lima' | 'mike' | 'november' | 'oscar' | 'papa' | 'quebec' | 'romeo' | 'sierra' | 'tango' | 'uniform' | 'victor' | 'whiskey' | 'xray' | 'yankee' | 'zulu' | '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '!' | '@' | '#' | '$' | '%' | '^' | '&' | '*' | '(' | ')' | '`' | '~' | '-' | '_' | '=' | '+' | '\\' | '|' | '[' | '{' | ']' | '}' | ';' | ':' | "'" | '"' | ',' | '<' | '.' | '>' | '/' | '?' | 'Left' | 'Right' | 'Up' | 'Down' | 'space-bar' | 'tab-key' | 'Enter' | 'page-up' | 'page-down' | 'Backspace' | 'delete' | 'Escape' | 'Home' | 'End' ) ;
        <69> = 'Press' <key> ;
        <70> = <key> 'Here' ;
        <71> = 'Space Bar' ;
        <72> = 'Tab Key' ;
        <special> = ('Left' | 'Right' | 'Up' | 'Down' | 'space-bar' | 'tab-key' | 'Enter' | 'page-up' | 'page-down' | 'Backspace' | 'delete' | 'escape' ) ;
        <mod> = 'Shift' | 'control-key' | 'Alt' ;
        <nn> = ('one' | 'two' | 'three' | 'four' | 'five' | 'six' | 'seven' | 'eight' | 'nine' | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 76 | 77 | 78 | 79 | 80 | 81 | 82 | 83 | 84 | 85 | 86 | 87 | 88 | 89 | 90 | 91 | 92 | 93 | 94 | 95 | 96 | 97 | 98 | 99) ;
        <73> = [ 'Press' ] (('Left' | 'Right' | 'Up' | 'Down' | 'space-bar' | 'tab-key' | 'Enter' | 'page-up' | 'page-down' | 'Backspace' | 'delete' | 'escape' ) ) <nn> ;
        <74> = [ 'Press' ] ('Shift' | 'control-key' | 'Alt' ) <key> <nn> ;
        <75> = [ 'Press' ] ('Shift' | 'control-key' | 'Alt' ) <mod> <key> <nn> ;
        <76> = [ 'Press' ] ('Shift' | 'control-key' | 'Alt' ) <mod> <mod> <key> <nn> ;
        <77> = 'Recent Documents' ;
        <78> = 'Run Program' ;
        <79> = 'Environment Variables' ;
        <1to20> = ('one' | 'two' | 'three' | 'four' | 'five' | 'six' | 'seven' | 'eight' | 'nine' | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20) ;
        <80> = 'Launch' <1to20> ;
        <81> = 'Launch Bar' ;
        <82> = 'Page' ;
        <83> = 'Backup' ;
        <84> = 'Escape' ;
        <any> = <1>|<2>|<3>|<4>|<5>|<6>|<7>|<8>|<9>|<10>|<11>|<12>|<13>|<14>|<15>|<16>|<17>|<18>|<19>|<20>|<21>|<22>|<23>|<24>|<25>|<26>|<27>|<28>|<29>|<30>|<31>|<32>|<33>|<34>|<35>|<36>|<37>|<38>|<39>|<40>|<41>|<42>|<43>|<44>|<45>|<46>|<47>|<48>|<49>|<50>|<51>|<52>|<53>|<54>|<55>|<56>|<57>|<58>|<59>|<60>|<61>|<62>|<63>|<64>|<65>|<66>|<67>|<68>|<69>|<70>|<71>|<72>|<73>|<74>|<75>|<76>|<77>|<78>|<79>|<80>|<81>|<82>|<83>|<84>;
        <sequence> exported = <any>;
    """
    
    def initialize(self):
        self.load(self.gramSpec)
        self.currentModule = ("","",0)
        self.ruleSet1 = ['sequence']

    def gotBegin(self,moduleInfo):
        window = moduleInfo[2]
        self.firstWord = 0
        # Return if same window and title as before
        if moduleInfo == self.currentModule: return None
        self.currentModule = moduleInfo

        self.deactivateAll()
        title = string.lower(moduleInfo[1])
        if string.find(title,'') >= 0:
            for rule in self.ruleSet1:
                self.activate(rule)

    def convert_number_word(self, word):
        if   word == 'zero':
            return '0'
        elif word == 'one':
            return '1'
        elif word == 'two':
            return '2'
        elif word == 'three':
            return '3'
        elif word == 'four':
            return '4'
        elif word == 'five':
            return '5'
        elif word == 'six':
            return '6'
        elif word == 'seven':
            return '7'
        elif word == 'eight':
            return '8'
        elif word == 'nine':
            return '9'
        else:
            return word

    # Switch Window
    def gotResults_1(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{Alt+Tab}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_1(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 8, 'Switch Window', e)
            self.firstWord = -1

    # Copy and Switch
    def gotResults_2(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+a}{Ctrl+c}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{Alt+Tab}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_2(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 9, 'Copy and Switch', e)
            self.firstWord = -1

    # Copy to (NatSpeak | Emacs | Composition)
    def gotResults_3(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+a}{Ctrl+c}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += 'switch'
            dragon_arg2 = ''
            dragon_arg2 += 'to'
            dragon_arg3 = ''
            word = fullResults[1 + self.firstWord][0]
            dragon_arg3 += word
            call_Dragon('HeardWord', 'ssssssss', [dragon_arg1, dragon_arg2, dragon_arg3])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_3(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 11, 'Copy to (NatSpeak | Emacs | Composition)', e)
            self.firstWord = -1

    # Close Here
    def gotResults_4(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '2'
            dragon_arg2 = ''
            dragon_arg2 += '1'
            call_Dragon('ButtonClick', 'ii', [dragon_arg1, dragon_arg2])
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            call_Dragon('Wait', 'i', [dragon_arg1])
            top_buffer += 'c'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_4(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 12, 'Close Here', e)
            self.firstWord = -1

    # Close Prompt
    def gotResults_5(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+Space}c'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_5(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 13, 'Close Prompt', e)
            self.firstWord = -1

    # (Switch | Next) View
    def gotResults_6(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Tab}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_6(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 18, '(Switch | Next) View', e)
            self.firstWord = -1

    # (Switch | Next) View <n>
    def gotResults_7(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Tab_'
            word = fullResults[2 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 19, '(Switch | Next) View <n>', e)
            self.firstWord = -1

    # Previous View
    def gotResults_8(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Shift+Tab}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_8(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 20, 'Previous View', e)
            self.firstWord = -1

    # Previous View <n>
    def gotResults_9(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Shift+Tab_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('_vocola.vcl', 21, 'Previous View <n>', e)
            self.firstWord = -1

    # Tab Back
    def gotResults_10(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Shift+Tab}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_10(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 23, 'Tab Back', e)
            self.firstWord = -1

    # Tab Back <n>
    def gotResults_11(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Shift+Tab_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('_vocola.vcl', 24, 'Tab Back <n>', e)
            self.firstWord = -1

    # (Expand | Collapse) That
    def gotResults_12(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            word = fullResults[0 + self.firstWord][0]
            if word == 'Expand':
                dragon_arg1 += '{Alt+ExtDown}'
            elif word == 'Collapse':
                dragon_arg1 += '{Alt+ExtUp}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_12(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 27, '(Expand | Collapse) That', e)
            self.firstWord = -1

    # Dragon Menu
    def gotResults_13(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{NumKey*}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_13(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 31, 'Dragon Menu', e)
            self.firstWord = -1

    # (Edit | Train) Words
    def gotResults_14(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{NumKey*}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            call_Dragon('Wait', 'i', [dragon_arg1])
            top_buffer += 'w'
            word = fullResults[0 + self.firstWord][0]
            if word == 'Edit':
                top_buffer += 'v'
            elif word == 'Train':
                top_buffer += 't'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_14(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 32, '(Edit | Train) Words', e)
            self.firstWord = -1

    # Save Speech Files
    def gotResults_15(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{NumKey*}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            call_Dragon('Wait', 'i', [dragon_arg1])
            top_buffer += 'ff'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_15(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 33, 'Save Speech Files', e)
            self.firstWord = -1

    # Exit NatSpeak
    def gotResults_16(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{NumKey*}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            call_Dragon('Wait', 'i', [dragon_arg1])
            top_buffer += 'e'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_16(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 34, 'Exit NatSpeak', e)
            self.firstWord = -1

    # Die Die
    def gotResults_17(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            call_Dragon('GoToSleep', '', [])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_17(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 35, 'Die Die', e)
            self.firstWord = -1

    # Hit Down
    def gotResults_18(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            call_Dragon('ButtonClick', 'ii', [])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_18(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 45, 'Hit Down', e)
            self.firstWord = -1

    # Hit Double
    def gotResults_19(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '1'
            dragon_arg2 = ''
            dragon_arg2 += '2'
            call_Dragon('ButtonClick', 'ii', [dragon_arg1, dragon_arg2])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_19(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 46, 'Hit Double', e)
            self.firstWord = -1

    # (Shift | Control | Alt) Click
    def gotResults_20(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            word = fullResults[0 + self.firstWord][0]
            if word == 'Shift':
                dragon_arg1 += '1'
            elif word == 'Control':
                dragon_arg1 += '2'
            elif word == 'Alt':
                dragon_arg1 += '3'
            call_Dragon('ShiftKey', 'ii', [dragon_arg1])
            top_buffer = do_flush(False, top_buffer);
            call_Dragon('ButtonClick', 'ii', [])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_20(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 47, '(Shift | Control | Alt) Click', e)
            self.firstWord = -1

    # Hit Start [Menu]
    def gotResults_21(self, words, fullResults):
        if self.firstWord<0:
            return
        opt = 1 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][0] != 'Menu':
            fullResults.insert(opt, 'dummy')
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{Ctrl+Esc}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_21(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 48, 'Hit Start [Menu]', e)
            self.firstWord = -1

    def get_n(self, list_buffer, functional, word):
        list_buffer += self.convert_number_word(word)
        return list_buffer

    def get_upDown(self, list_buffer, functional, word):
        if word == 'Up':
            list_buffer += '-'
        elif word == 'Down':
            list_buffer += ''
        return list_buffer

    def get_leftRight(self, list_buffer, functional, word):
        if word == 'Left':
            list_buffer += '-'
        elif word == 'Right':
            list_buffer += ''
        return list_buffer

    # Drag <n> <upDown>
    def gotResults_22(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            call_Dragon('RememberPoint', '', [])
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '2'
            dragon_arg2 = ''
            eval_template2_arg1 = ''
            eval_template2_arg1 += '15*%a'
            eval_template2_arg2 = ''
            eval_template2_arg2 += '0'
            dragon_arg2 += eval_template(eval_template2_arg1, eval_template2_arg2)
            dragon_arg3 = ''
            eval_template2_arg1 = ''
            eval_template2_arg1 += '15*%a'
            eval_template2_arg2 = ''
            word = fullResults[2 + self.firstWord][0]
            eval_template2_arg2 = self.get_upDown(eval_template2_arg2, True, word)
            word = fullResults[1 + self.firstWord][0]
            eval_template2_arg2 = self.get_n(eval_template2_arg2, True, word)
            dragon_arg3 += eval_template(eval_template2_arg1, eval_template2_arg2)
            call_Dragon('SetMousePosition', 'iii', [dragon_arg1, dragon_arg2, dragon_arg3])
            top_buffer = do_flush(False, top_buffer);
            call_Dragon('DragToPoint', 'i', [])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 63, 'Drag <n> <upDown>', e)
            self.firstWord = -1

    # Drag <n> <leftRight>
    def gotResults_23(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            call_Dragon('RememberPoint', '', [])
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '2'
            dragon_arg2 = ''
            eval_template2_arg1 = ''
            eval_template2_arg1 += '15*%a'
            eval_template2_arg2 = ''
            word = fullResults[2 + self.firstWord][0]
            eval_template2_arg2 = self.get_leftRight(eval_template2_arg2, True, word)
            word = fullResults[1 + self.firstWord][0]
            eval_template2_arg2 = self.get_n(eval_template2_arg2, True, word)
            dragon_arg2 += eval_template(eval_template2_arg1, eval_template2_arg2)
            dragon_arg3 = ''
            eval_template2_arg1 = ''
            eval_template2_arg1 += '15*%a'
            eval_template2_arg2 = ''
            eval_template2_arg2 += '0'
            dragon_arg3 += eval_template(eval_template2_arg1, eval_template2_arg2)
            call_Dragon('SetMousePosition', 'iii', [dragon_arg1, dragon_arg2, dragon_arg3])
            top_buffer = do_flush(False, top_buffer);
            call_Dragon('DragToPoint', 'i', [])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 64, 'Drag <n> <leftRight>', e)
            self.firstWord = -1

    # Window <direction>
    def gotResults_24(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Win+'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_direction(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('_vocola.vcl', 68, 'Window <direction>', e)
            self.firstWord = -1

    def get_direction(self, list_buffer, functional, word):
        list_buffer += word
        return list_buffer

    def get_left_right(self, list_buffer, functional, word):
        list_buffer += word
        return list_buffer

    def get_start_end(self, list_buffer, functional, word):
        if word == 'Start':
            list_buffer += '{Home}'
        elif word == 'End':
            list_buffer += '{End}'
        return list_buffer

    def get_compass(self, list_buffer, functional, word):
        if word == 'North':
            list_buffer += '{Shift+Ctrl+Home}'
        elif word == 'South':
            list_buffer += '{Shift+Ctrl+End}'
        elif word == 'East':
            list_buffer += '{Shift+End}'
        elif word == 'West':
            list_buffer += '{Shift+Home}'
        return list_buffer

    # Kill (Char | 1 | One)
    def gotResults_25(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_25(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 98, 'Kill (Char | 1 | One)', e)
            self.firstWord = -1

    # Kill Back [1]
    def gotResults_26(self, words, fullResults):
        if self.firstWord<0:
            return
        opt = 1 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][0] != '1':
            fullResults.insert(opt, 'dummy')
        try:
            top_buffer = ''
            top_buffer += '{Backspace}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_26(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 99, 'Kill Back [1]', e)
            self.firstWord = -1

    # Kill <n>
    def gotResults_27(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Del_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('_vocola.vcl', 100, 'Kill <n>', e)
            self.firstWord = -1

    # [Kill] Back <n>
    def gotResults_28(self, words, fullResults):
        if self.firstWord<0:
            return
        opt = 0 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][0] != 'Kill':
            fullResults.insert(opt, 'dummy')
        try:
            top_buffer = ''
            top_buffer += '{Backspace_'
            word = fullResults[2 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 101, '[Kill] Back <n>', e)
            self.firstWord = -1

    # [One] Word <left_right>
    def gotResults_29(self, words, fullResults):
        if self.firstWord<0:
            return
        opt = 0 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][0] != 'One':
            fullResults.insert(opt, 'dummy')
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+'
            word = fullResults[2 + self.firstWord][0]
            top_buffer = self.get_left_right(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 104, '[One] Word <left_right>', e)
            self.firstWord = -1

    # <n> Words <left_right>
    def gotResults_30(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+'
            word = fullResults[2 + self.firstWord][0]
            top_buffer = self.get_left_right(top_buffer, False, word)
            top_buffer += '_'
            word = fullResults[0 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 105, '<n> Words <left_right>', e)
            self.firstWord = -1

    # Kill Word
    def gotResults_31(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Right_2}{Ctrl+Left}{Shift+Ctrl+Right}'
            top_buffer += '{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_31(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 106, 'Kill Word', e)
            self.firstWord = -1

    # Kill <n> Words
    def gotResults_32(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Right_2}{Ctrl+Left}{Shift+Ctrl+Right_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 107, 'Kill <n> Words', e)
            self.firstWord = -1

    # Kill Back Word
    def gotResults_33(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Left}{Ctrl+Right}{Shift+Ctrl+Left}'
            top_buffer += '{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_33(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 108, 'Kill Back Word', e)
            self.firstWord = -1

    # Kill Back <n> Words
    def gotResults_34(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Left}{Ctrl+Right}{Shift+Ctrl+Left_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 109, 'Kill Back <n> Words', e)
            self.firstWord = -1

    # Line <start_end>
    def gotResults_35(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_start_end(top_buffer, False, word)
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('_vocola.vcl', 112, 'Line <start_end>', e)
            self.firstWord = -1

    # Line Here
    def gotResults_36(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Enter}{Left}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_36(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 115, 'Line Here', e)
            self.firstWord = -1

    # Copy Line
    def gotResults_37(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{home}{Shift+Down}{Shift+Home}{Ctrl+c}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_37(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 116, 'Copy Line', e)
            self.firstWord = -1

    # Kill Line
    def gotResults_38(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{home}{Shift+Down}{Shift+Home}{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_38(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 117, 'Kill Line', e)
            self.firstWord = -1

    # Kill Back Line
    def gotResults_39(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{home}{Shift+Up}'
            top_buffer += '{Shift+Home}{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_39(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 118, 'Kill Back Line', e)
            self.firstWord = -1

    # Kill <n> Lines
    def gotResults_40(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{home}{Shift+Down_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}{Shift+Home}{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 119, 'Kill <n> Lines', e)
            self.firstWord = -1

    # Kill Back <n> Lines
    def gotResults_41(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{home}{Shift+Up_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}'
            top_buffer += '{Shift+Home}{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('_vocola.vcl', 120, 'Kill Back <n> Lines', e)
            self.firstWord = -1

    # Kill Here
    def gotResults_42(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Shift+End}{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_42(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 121, 'Kill Here', e)
            self.firstWord = -1

    # Kill Back Here
    def gotResults_43(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Shift+Home}{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_43(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 122, 'Kill Back Here', e)
            self.firstWord = -1

    # Duplicate Line
    def gotResults_44(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{home}{Shift+Down}{Shift+Home}{Ctrl+c}{Home}{Ctrl+v}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_44(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 123, 'Duplicate Line', e)
            self.firstWord = -1

    # Graph Start
    def gotResults_45(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Up}{Right}{Home}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_45(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 126, 'Graph Start', e)
            self.firstWord = -1

    # Graph End
    def gotResults_46(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Down}{Left_2}{End}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_46(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 127, 'Graph End', e)
            self.firstWord = -1

    # (Paragraph | Graph) Here
    def gotResults_47(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Enter}{Enter}{Left}{Left}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_47(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 128, '(Paragraph | Graph) Here', e)
            self.firstWord = -1

    # Open (Graph | Line)
    def gotResults_48(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Enter}{Enter}{Left}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_48(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 129, 'Open (Graph | Line)', e)
            self.firstWord = -1

    # Copy Graph
    def gotResults_49(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Down}{Shift+Ctrl+Up}{Ctrl+c}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_49(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 130, 'Copy Graph', e)
            self.firstWord = -1

    # Kill Graph
    def gotResults_50(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Down}{Shift+Ctrl+Up}{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_50(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 131, 'Kill Graph', e)
            self.firstWord = -1

    # Duplicate Graph
    def gotResults_51(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Down}{Shift+Ctrl+Up}{Ctrl+c}{Home}{Ctrl+v}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_51(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 132, 'Duplicate Graph', e)
            self.firstWord = -1

    # Flow Start
    def gotResults_52(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Home}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_52(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 135, 'Flow Start', e)
            self.firstWord = -1

    # Flow End
    def gotResults_53(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+End}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_53(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 136, 'Flow End', e)
            self.firstWord = -1

    # Select All
    def gotResults_54(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+a}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_54(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 138, 'Select All', e)
            self.firstWord = -1

    # Copy All
    def gotResults_55(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+a}{Ctrl+c}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_55(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 139, 'Copy All', e)
            self.firstWord = -1

    # (Cut | Kill) All
    def gotResults_56(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+a}{Ctrl+x}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_56(words[2:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 140, '(Cut | Kill) All', e)
            self.firstWord = -1

    # Kill Flow Here
    def gotResults_57(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Shift+End}'
            top_buffer += '{Ctrl+x}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_57(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 141, 'Kill Flow Here', e)
            self.firstWord = -1

    # Kill Back Flow Here
    def gotResults_58(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Shift+Home}{Ctrl+x}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_58(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 142, 'Kill Back Flow Here', e)
            self.firstWord = -1

    # Replace All
    def gotResults_59(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+a}{Del}{Ctrl+v}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_59(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 143, 'Replace All', e)
            self.firstWord = -1

    # Kill That
    def gotResults_60(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_60(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 146, 'Kill That', e)
            self.firstWord = -1

    # Yank That
    def gotResults_61(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+v}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_61(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 150, 'Yank That', e)
            self.firstWord = -1

    # Paste Here
    def gotResults_62(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            call_Dragon('ButtonClick', 'ii', [])
            top_buffer += '{Ctrl+v}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_62(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 151, 'Paste Here', e)
            self.firstWord = -1

    # Duplicate That
    def gotResults_63(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+c}{Left}{Ctrl+v}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_63(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 152, 'Duplicate That', e)
            self.firstWord = -1

    # Keep That
    def gotResults_64(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+c}{Ctrl+a}{Del}{Ctrl+v}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_64(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 153, 'Keep That', e)
            self.firstWord = -1

    # Select <compass>
    def gotResults_65(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_compass(top_buffer, False, word)
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('_vocola.vcl', 154, 'Select <compass>', e)
            self.firstWord = -1

    # undo that <n>
    def gotResults_66(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+z_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('_vocola.vcl', 157, 'undo that <n>', e)
            self.firstWord = -1

    # Camel [Case] That
    def gotResults_67(self, words, fullResults):
        if self.firstWord<0:
            return
        opt = 1 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][0] != 'Case':
            fullResults.insert(opt, 'dummy')
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '\\Cap'
            dragon_arg2 = ''
            dragon_arg2 += 'That'
            call_Dragon('HeardWord', 'ssssssss', [dragon_arg1, dragon_arg2])
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += 'compound'
            dragon_arg2 = ''
            dragon_arg2 += 'that'
            call_Dragon('HeardWord', 'ssssssss', [dragon_arg1, dragon_arg2])
            top_buffer += '{Ctrl+Left}'
            top_buffer += '{Shift+Right}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '\\No-Caps'
            dragon_arg2 = ''
            dragon_arg2 += 'That'
            call_Dragon('HeardWord', 'ssssssss', [dragon_arg1, dragon_arg2])
            top_buffer += '{Ctrl+Right}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
            if len(words) > 3: self.gotResults_67(words[3:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 159, 'Camel [Case] That', e)
            self.firstWord = -1

    # (Cap | Up Case) <n>
    def gotResults_68(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Shift+Right_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_n(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '\\All-Caps'
            dragon_arg2 = ''
            dragon_arg2 += 'That'
            call_Dragon('HeardWord', 'ssssssss', [dragon_arg1, dragon_arg2])
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('_vocola.vcl', 160, '(Cap | Up Case) <n>', e)
            self.firstWord = -1

    def get_key(self, list_buffer, functional, word):
        if word == 'alpha':
            list_buffer += 'a'
        elif word == 'bravo':
            list_buffer += 'b'
        elif word == 'charlie':
            list_buffer += 'c'
        elif word == 'delta':
            list_buffer += 'd'
        elif word == 'echo':
            list_buffer += 'e'
        elif word == 'foxtrot':
            list_buffer += 'f'
        elif word == 'golf':
            list_buffer += 'g'
        elif word == 'hotel':
            list_buffer += 'h'
        elif word == 'india':
            list_buffer += 'i'
        elif word == 'juliett':
            list_buffer += 'j'
        elif word == 'kilo':
            list_buffer += 'k'
        elif word == 'lima':
            list_buffer += 'l'
        elif word == 'mike':
            list_buffer += 'm'
        elif word == 'november':
            list_buffer += 'n'
        elif word == 'oscar':
            list_buffer += 'o'
        elif word == 'papa':
            list_buffer += 'p'
        elif word == 'quebec':
            list_buffer += 'q'
        elif word == 'romeo':
            list_buffer += 'r'
        elif word == 'sierra':
            list_buffer += 's'
        elif word == 'tango':
            list_buffer += 't'
        elif word == 'uniform':
            list_buffer += 'u'
        elif word == 'victor':
            list_buffer += 'v'
        elif word == 'whiskey':
            list_buffer += 'w'
        elif word == 'xray':
            list_buffer += 'x'
        elif word == 'yankee':
            list_buffer += 'y'
        elif word == 'zulu':
            list_buffer += 'z'
        elif word == '0':
            list_buffer += '0'
        elif word == '1':
            list_buffer += '1'
        elif word == '2':
            list_buffer += '2'
        elif word == '3':
            list_buffer += '3'
        elif word == '4':
            list_buffer += '4'
        elif word == '5':
            list_buffer += '5'
        elif word == '6':
            list_buffer += '6'
        elif word == '7':
            list_buffer += '7'
        elif word == '8':
            list_buffer += '8'
        elif word == '9':
            list_buffer += '9'
        elif word == '!':
            list_buffer += '!'
        elif word == '@':
            list_buffer += '@'
        elif word == '#':
            list_buffer += '#'
        elif word == '$':
            list_buffer += '$'
        elif word == '%':
            list_buffer += '%'
        elif word == '^':
            list_buffer += '^'
        elif word == '&':
            list_buffer += '&'
        elif word == '*':
            list_buffer += '*'
        elif word == '(':
            list_buffer += '('
        elif word == ')':
            list_buffer += ')'
        elif word == '`':
            list_buffer += '`'
        elif word == '~':
            list_buffer += '~'
        elif word == '-':
            list_buffer += '-'
        elif word == '_':
            list_buffer += '_'
        elif word == '=':
            list_buffer += '='
        elif word == '+':
            list_buffer += '+'
        elif word == '\\':
            list_buffer += '\\'
        elif word == '|':
            list_buffer += '|'
        elif word == '[':
            list_buffer += '['
        elif word == '{':
            list_buffer += '{'
        elif word == ']':
            list_buffer += ']'
        elif word == '}':
            list_buffer += '}'
        elif word == ';':
            list_buffer += ';'
        elif word == ':':
            list_buffer += ':'
        elif word == '\'':
            list_buffer += '\''
        elif word == '"':
            list_buffer += '"'
        elif word == ',':
            list_buffer += ','
        elif word == '<':
            list_buffer += '<'
        elif word == '.':
            list_buffer += '.'
        elif word == '>':
            list_buffer += '>'
        elif word == '/':
            list_buffer += '/'
        elif word == '?':
            list_buffer += '?'
        elif word == 'Left':
            list_buffer += 'Left'
        elif word == 'Right':
            list_buffer += 'Right'
        elif word == 'Up':
            list_buffer += 'Up'
        elif word == 'Down':
            list_buffer += 'Down'
        elif word == 'space-bar':
            list_buffer += ' '
        elif word == 'tab-key':
            list_buffer += 'Tab'
        elif word == 'Enter':
            list_buffer += 'Enter'
        elif word == 'page-up':
            list_buffer += 'PgUp'
        elif word == 'page-down':
            list_buffer += 'PgDn'
        elif word == 'Backspace':
            list_buffer += 'Backspace'
        elif word == 'delete':
            list_buffer += 'Del'
        elif word == 'Escape':
            list_buffer += 'Esc'
        elif word == 'Home':
            list_buffer += 'Home'
        elif word == 'End':
            list_buffer += 'End'
        return list_buffer

    # Press <key>
    def gotResults_69(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_key(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('keys.vch', 20, 'Press <key>', e)
            self.firstWord = -1

    # <key> Here
    def gotResults_70(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            call_Dragon('ButtonClick', 'ii', [])
            top_buffer += '{'
            word = fullResults[0 + self.firstWord][0]
            top_buffer = self.get_key(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('keys.vch', 21, '<key> Here', e)
            self.firstWord = -1

    # Space Bar
    def gotResults_71(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += ' '
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_71(words[1:], fullResults)
        except Exception, e:
            handle_error('keys.vch', 23, 'Space Bar', e)
            self.firstWord = -1

    # Tab Key
    def gotResults_72(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Tab}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_72(words[1:], fullResults)
        except Exception, e:
            handle_error('keys.vch', 24, 'Tab Key', e)
            self.firstWord = -1

    def get_special(self, list_buffer, functional, word):
        if word == 'Left':
            list_buffer += 'Left'
        elif word == 'Right':
            list_buffer += 'Right'
        elif word == 'Up':
            list_buffer += 'Up'
        elif word == 'Down':
            list_buffer += 'Down'
        elif word == 'space-bar':
            list_buffer += ' '
        elif word == 'tab-key':
            list_buffer += 'Tab'
        elif word == 'Enter':
            list_buffer += 'Enter'
        elif word == 'page-up':
            list_buffer += 'PgUp'
        elif word == 'page-down':
            list_buffer += 'PgDn'
        elif word == 'Backspace':
            list_buffer += 'Backspace'
        elif word == 'delete':
            list_buffer += 'Del'
        elif word == 'escape':
            list_buffer += 'Esc'
        return list_buffer

    def get_mod(self, list_buffer, functional, word):
        if word == 'Shift':
            list_buffer += 'Shift'
        elif word == 'control-key':
            list_buffer += 'Ctrl'
        elif word == 'Alt':
            list_buffer += 'Alt'
        return list_buffer

    def get_nn(self, list_buffer, functional, word):
        list_buffer += self.convert_number_word(word)
        return list_buffer

    # [Press] ((Left | Right | Up | Down | space-bar | tab-key | Enter | page-up | page-down | Backspace | delete | escape)) <nn>
    def gotResults_73(self, words, fullResults):
        if self.firstWord<0:
            return
        opt = 0 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][0] != 'Press':
            fullResults.insert(opt, 'dummy')
        try:
            top_buffer = ''
            top_buffer += '{'
            word = fullResults[1 + self.firstWord][0]
            if word == 'Left':
                top_buffer += 'Left'
            elif word == 'Right':
                top_buffer += 'Right'
            elif word == 'Up':
                top_buffer += 'Up'
            elif word == 'Down':
                top_buffer += 'Down'
            elif word == 'space-bar':
                top_buffer += ' '
            elif word == 'tab-key':
                top_buffer += 'Tab'
            elif word == 'Enter':
                top_buffer += 'Enter'
            elif word == 'page-up':
                top_buffer += 'PgUp'
            elif word == 'page-down':
                top_buffer += 'PgDn'
            elif word == 'Backspace':
                top_buffer += 'Backspace'
            elif word == 'delete':
                top_buffer += 'Del'
            elif word == 'escape':
                top_buffer += 'Esc'
            top_buffer += '_'
            word = fullResults[2 + self.firstWord][0]
            top_buffer = self.get_nn(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 3
        except Exception, e:
            handle_error('keys.vch', 36, '[Press] ((Left | Right | Up | Down | space-bar | tab-key | Enter | page-up | page-down | Backspace | delete | escape)) <nn>', e)
            self.firstWord = -1

    # [Press] (Shift | control-key | Alt) <key> <nn>
    def gotResults_74(self, words, fullResults):
        if self.firstWord<0:
            return
        opt = 0 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][0] != 'Press':
            fullResults.insert(opt, 'dummy')
        try:
            top_buffer = ''
            top_buffer += '{'
            word = fullResults[1 + self.firstWord][0]
            if word == 'Shift':
                top_buffer += 'Shift'
            elif word == 'control-key':
                top_buffer += 'Ctrl'
            elif word == 'Alt':
                top_buffer += 'Alt'
            top_buffer += '+'
            word = fullResults[2 + self.firstWord][0]
            top_buffer = self.get_key(top_buffer, False, word)
            top_buffer += '_'
            word = fullResults[3 + self.firstWord][0]
            top_buffer = self.get_nn(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 4
        except Exception, e:
            handle_error('keys.vch', 37, '[Press] (Shift | control-key | Alt) <key> <nn>', e)
            self.firstWord = -1

    # [Press] (Shift | control-key | Alt) <mod> <key> <nn>
    def gotResults_75(self, words, fullResults):
        if self.firstWord<0:
            return
        opt = 0 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][0] != 'Press':
            fullResults.insert(opt, 'dummy')
        try:
            top_buffer = ''
            top_buffer += '{'
            word = fullResults[1 + self.firstWord][0]
            if word == 'Shift':
                top_buffer += 'Shift'
            elif word == 'control-key':
                top_buffer += 'Ctrl'
            elif word == 'Alt':
                top_buffer += 'Alt'
            top_buffer += '+'
            word = fullResults[2 + self.firstWord][0]
            top_buffer = self.get_mod(top_buffer, False, word)
            top_buffer += '+'
            word = fullResults[3 + self.firstWord][0]
            top_buffer = self.get_key(top_buffer, False, word)
            top_buffer += '_'
            word = fullResults[4 + self.firstWord][0]
            top_buffer = self.get_nn(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 5
        except Exception, e:
            handle_error('keys.vch', 38, '[Press] (Shift | control-key | Alt) <mod> <key> <nn>', e)
            self.firstWord = -1

    # [Press] (Shift | control-key | Alt) <mod> <mod> <key> <nn>
    def gotResults_76(self, words, fullResults):
        if self.firstWord<0:
            return
        opt = 0 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][0] != 'Press':
            fullResults.insert(opt, 'dummy')
        try:
            top_buffer = ''
            top_buffer += '{'
            word = fullResults[1 + self.firstWord][0]
            if word == 'Shift':
                top_buffer += 'Shift'
            elif word == 'control-key':
                top_buffer += 'Ctrl'
            elif word == 'Alt':
                top_buffer += 'Alt'
            top_buffer += '+'
            word = fullResults[2 + self.firstWord][0]
            top_buffer = self.get_mod(top_buffer, False, word)
            top_buffer += '+'
            word = fullResults[3 + self.firstWord][0]
            top_buffer = self.get_mod(top_buffer, False, word)
            top_buffer += '+'
            word = fullResults[4 + self.firstWord][0]
            top_buffer = self.get_key(top_buffer, False, word)
            top_buffer += '_'
            word = fullResults[5 + self.firstWord][0]
            top_buffer = self.get_nn(top_buffer, False, word)
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 6
        except Exception, e:
            handle_error('keys.vch', 39, '[Press] (Shift | control-key | Alt) <mod> <mod> <key> <nn>', e)
            self.firstWord = -1

    # Recent Documents
    def gotResults_77(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{Ctrl+Esc}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer += '{Up_6}{Right}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_77(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 167, 'Recent Documents', e)
            self.firstWord = -1

    # Run Program
    def gotResults_78(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{Ctrl+Esc}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer += '{Up_2}{Enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_78(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 168, 'Run Program', e)
            self.firstWord = -1

    # Environment Variables
    def gotResults_79(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += 'C:\\WINNT\\System32\\SYSDM.CPL'
            call_Dragon('AppBringUp', 'ssis', [dragon_arg1])
            top_buffer += '{Shift+Tab}{Right_4}{Alt+e}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_79(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 172, 'Environment Variables', e)
            self.firstWord = -1

    def get_1to20(self, list_buffer, functional, word):
        list_buffer += self.convert_number_word(word)
        return list_buffer

    # Launch <1to20>
    def gotResults_80(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{Ctrl+Esc}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer += '{Esc}{Tab}'
            top_buffer += '{Left}{Right_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_1to20(top_buffer, False, word)
            top_buffer += '}'
            top_buffer += ' '
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('_vocola.vcl', 186, 'Launch <1to20>', e)
            self.firstWord = -1

    # Launch Bar
    def gotResults_81(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '{Ctrl+Esc}'
            call_Dragon('SendSystemKeys', 'si', [dragon_arg1])
            top_buffer += '{Esc}{Tab}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_81(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 187, 'Launch Bar', e)
            self.firstWord = -1

    # Page
    def gotResults_82(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{PgDn}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_82(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 205, 'Page', e)
            self.firstWord = -1

    # Backup
    def gotResults_83(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{PgUp}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_83(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 206, 'Backup', e)
            self.firstWord = -1

    # Escape
    def gotResults_84(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Esc}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_84(words[1:], fullResults)
        except Exception, e:
            handle_error('_vocola.vcl', 207, 'Escape', e)
            self.firstWord = -1

thisGrammar = ThisGrammar()
thisGrammar.initialize()

def unload():
    global thisGrammar
    if thisGrammar: thisGrammar.unload()
    thisGrammar = None
